
export const GET_LIST_COURSE = "GET_LIST_COURSE";

export const ADD_COURSE = "ADD_COURSE";

export const EDIT_COURSE = "EDIT_COURSE";

export const DELETE_COURSE = "DELETE_COURSE";

export const FIND_COURSE = "FIND_COURSE";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_CATEGORY_COURSES = "GET_CATEGORY_COURSES";

