export const GET_DETAIL_COURSE = {
    REQUEST: "GET_DETAIL_COURSE_REQUEST",
    SUCCESS: "GET_DETAIL_COURSE_SUCCESS",
    FAILED: "GET_DETAIL_COURSE_FAILED"
};

export const GET_ENROLL_COURSES = {
    REQUEST: "GET_ENROLL_COURSES_REQUEST",
    SUCCESS: "GET_ENROLL_COURSES_SUCCESS",
    FAILED: "GET_ENROLL_COURSES_FAILED"
};

export const GET_WAITING_ENROLL_COURSES = {
    REQUEST: "GET_WAITING_ENROLL_COURSES_REQUEST",
    SUCCESS: "GET_WAITING_ENROLL_COURSES_SUCCESS",
    FAILED: "GET_WAITING_ENROLL_COURSES_FAILED"
}

export const GET_NOT_ENROLL_COURSES = "GET_NOT_ENROLL_COURSES";

export const ENROLL = "ENROLL";

export const DISENROLL = "DISENROLL";