export const GET_COURSES = {
    REQUEST: "GET_COURSES_REQUEST",
    SUCCESS: "GET_COURSES_SUCCESS",
    FAILED: "GET_COURSES_FAILURE"
};

export const ADD_COURSE = {
    REQUEST: "ADD_COURSE_REQUEST",
    SUCCESS: "ADD_COURSE_SUCCESS", 
    FAILED: "ADD_COURSE_FAILURE"
};

export const EDIT_COURSE = {
    REQUEST: "EDIT_COURSE_REQUEST",
    SUCCESS: "EDIT_COURSE_SUCCESS",
    FAILED: "EDIT_COURSE_FAILURE"
};

export const DELETE_COURSE = {
    REQUEST: "DELETE_COURSE_REQUEST",
    SUCCESS: "DELETE_COURSE_SUCCESS",
    FAILED: "DELETE_COURSE_FAILURE"
};

export const GET_CATEGORIES = {
    REQUEST: "GET_CATEGORIES_REQUEST",
    SUCCESS: "GET_CATEGORIES_SUCCESS",
    FAILED: "GET_CATEGORIES_FAILURE"
};

export const GET_CATEGORY_COURSES = {
    REQUEST: "GET_CATEGORY_COURSES_REQUEST",
    SUCCESS: "GET_CATEGORY_COURSES_SUCCESS",
    FAILED: "GET_CATEGORY_COURSES_FAILURE"
};

export const FIND_COURSE = "FIND_COURSE";