export const GET_INFO_COURSE = "GET_INFO_COURSE";

export const GET_ENROLL_COURSES = "GET_ENROLL_COURSES";

export const GET_NOT_ENROLL_COURSES = "GET_NOT_ENROLL_COURSES";

export const GET_WAITING_ENROLL_COURSES = "GET_WAITING_ENROLL_COURSES";

export const ENROLL = "ENROLL";

export const DISENROLL = "DISENROLL";