export const OPEN_LOGIN_SIDEBAR = "OPEN_LOGIN_SIDEBAR";

export const CLOSE_LOGIN_SIDEBAR = "CLOSE_LOGIN_SIDEBAR";

export const OPEN_SIGN_UP_SIDEBAR = "OPEN_SIGN_UP_SIDEBAR";

export const CLOSE_SIGN_UP_SIDEBAR = "CLOSE_SIGN_UP_SIDEBAR";