export const USER_SIGN_UP = {
    REQUEST: "USER_SIGN_UP_REQUEST",
    SUCCESS: "USER_SIGN_UP_SUCCESS",
    FAILED: "USER_SIGN_UP_FAILED"
};

export const USER_LOGIN = {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAILED: "USER_LOGIN_FAILED"
}

export const USER_ENROLL = {
    REQUEST: "USER_ENROLL_REQUEST",
    SUCCESS: "USER_ENROLL_SUCCESS",
    FAILED: "USER_ENROLL_FAILED"
}
export const ADMIN_LOGIN = "ADMIN_LOGIN";

export const USER_LOG_OUT = "USER_LOG_OUT";

export const USER_PROFILE = {
    REQUEST: "USER_PROFILE_REQUEST",
    SUCCESS: "USER_PROFILE_SUCCESS",
    FAILED: "USER_PROFILE_FAILED"
};
